name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        # URL of gitHub public upstream repo
        upstream_repo: https://github.com/wppconnect-team/wppconnect.git
        # Branch to merge from upstream (defaults to downstream branch)
        upstream_branch: master
        # Branch to merge into downstream
        downstream_branch: master
        # GitHub Bot token
        token: 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
