name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Fork Sync
      # You may pin to the exact commit or the version.
      # uses: tgymnich/fork-sync@0cc6ac48fd51415e7c34e5b8823021bc952a5f5f
        uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.AUTH_TOKEN }}
          # Branch to track
          head: master # optional, default is master
          # Branch to keep updated
          base: master # optional, default is master
          # Merge method to use
          merge_method: merge # optional, default is merge
