name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.AUTH_TOKEN }}
    
    - name: Configuração de Usuário e E-mail do Git
      run: |
        git config --global user.email "eduardopolicarpo@gmail.com"
        git config --global user.name "edupoli"

    - name: Configurar remoto upstream com token
      run: |
        git remote add upstream https://x-access-token:${{ secrets.AUTH_TOKEN }}@github.com/wppconnect-team/wppconnect

    - name: Sincronizar com upstream
      run: |
        git fetch upstream
        git checkout master
        git merge upstream/master

    - name: Empurrar alterações para o fork
      run: git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}

